#!/usr/bin/bash
function getFilePath
{
    local -r key="$1"
    local -Ar fileNames=(
        # hardware dim related files
        ["hw_brightness_tracker"]="hardware_brightness_tracker"
        ["hw_brightness_ctl"]="hardware_brightness_controller"
        ["max_hw_brightness"]="max_hardware_brightness"
        ["og_hw_dim_enabled"]="og_hardware_dim_enabled"
        ["og_hw_dim_source_code"]="og_hardware_dim_source_code.c"
        ["og_hw_dim_exec"]="og_hardware_dim"

        # software dim related files
        ["sw_brightness_tracker"]="software_brightness_tracker"
        ["sw_dim_xrandr_verbose_cache"]="software_dim_buffer"
        ["og_sw_dim_exec"]="og_software_dim"
    );

    echo "${OG_DIM_DIR}/${fileNames["${key}"]}"
}

# might have to make getRealPath if og_hardware_dim doesn't play nice with symbolic links

function isOgdimRunningInValidEnv
{
    # only run program from symbolic link to make handling of software
    # and hardware versions of ogdim cleaner and make version ctl easier
    if ! [[ -L "$0" ]]; then return 1; fi
    if [[ -z "$OG_DIM_DIR" ]]; then return 2; fi
}

function getUserInputFilePath
{
    local -r prompt="$1"
    read -rp "$prompt" path

    if ! [[ -e "$path" ]]; then
        echo "Make sure file '$path' exists!!!!" 1>&2
        return 1
    fi

    echo "$path"
}

function makeHardwareDimExecutable
{
    local -r exec_name="$(getFilePath og_hw_dim_exec)"
    local -r source_name="$(getFilePath og_hw_dim_source_code)"

    gcc -O2 -o "$exec_name" "$source_name"
    echo 'Need root privileges to setup og hardware dim executable!'
    sudo chown root:root "$exec_name"
    sudo chmod 4555 "$exec_name"
    echo 'Finished setting up og hardware dim!!'
}

# will only recompile when source code is older than executable
function updateHardwareDimExecutable
{
    # if it ever gets more complicated, its time to use a makefile
    local -r exec_name="$(getFilePath og_hw_dim_exec)"
    local -r source_name="$(getFilePath og_hw_dim_source_code)"
    local -ri source_code_modification_time="$(stat -L -c'%Y' "$source_name")"
    local -ri exec_modification_time="$(stat -L -c'%Y' "$exec_name")"

    if ! [[ "$source_code_modification_time" -gt "$exec_modification_time" ]]; then return 0; fi
    makeHardwareDimExecutable
}

function isHardwareDimEnabled
{
    [[ -e "$(getFilePath og_hw_dim_enabled)" ]]
}

function initHardwareDim
{
    read -rp 'Enable hardware dimming? (must have software dimmable backlight) [y/n]: ' response
    if grep -q -v -i '^y' <<< "$response"; then return 0; fi

    local brightness_ctl
    local brightness_max
    local sourceCode
    # || exit 1 is done so if getUserInputFilePath returns a non zero code, the program stops
    brightness_ctl="$(getUserInputFilePath "Provide full path to brightness controller file: ")" || exit 1
    brightness_max="$(getUserInputFilePath "Provide full path to brightness max file: ")" || exit 1
    sourceCode="$(getUserInputFilePath "Provide full path to hardware dim source code: ")" || exit

    ln -s "${brightness_ctl}" "$(getFilePath hw_brightness_ctl)"
    ln -s "${brightness_max}" "$(getFilePath max_hw_brightness)"
    ln -s "${sourceCode}" "$(getFilePath og_hw_dim_source_code)"

    touch "$(getFilePath og_hw_dim_enabled)" # if file exists, hw dim is enabled

    # og_hardware_dim requires tracker file to be owned by root and have
    # restrictive permissions, since set uid on exec, need to be safe!
    local -r brightness_tracker="$(getFilePath hw_brightness_tracker)"
    touch "$brightness_tracker"
    echo 'Need root privileges to setup brightness tracker file for hardware dim executable!'
    sudo chown root:root "$brightness_tracker"
    sudo chmod 644 "$brightness_tracker"
    echo 'Finished setting up brightness tracker!'
    makeHardwareDimExecutable
}

function initSoftwareDim
{
    local sw_dim_script
    sw_dim_script="$(getUserInputFilePath "Provide full path to software dim executable script: ")" || exit 1

    ln -s "$sw_dim_script" "$(getFilePath og_sw_dim_exec)"

    # no special permissions on the following files since
    # og_software_dim runs in normal user mode not root
    touch "$(getFilePath sw_brightness_tracker)"
    touch "$(getFilePath sw_dim_xrandr_verbose_cache)"
}


function initSetup
{
    echo 'Starting init setup'
    echo 'Checking ogdim environment'
    if ! isOgdimRunningInValidEnv; then
    {
        local -ar error_messages=(
            "$0 must be a symbolic link to original file in my linux utils folder!"
            "OG_DIM_DIR environment variable must be set!"
        )
        local -ir error_code="$?"
        local -ir error_index=$(( error_code - 1 ))

        echo "${error_messages["$error_index"]}"
        exit 1
    } 1>&2
    fi
    echo 'ogdim environment: passed'


    mkdir -p "$OG_DIM_DIR"
    initHardwareDim
    initSoftwareDim
    echo 'Finished init setup!'
}

function runHardwareDim
{
    local -ri hardware_dim_value="$1"
    updateHardwareDimExecutable
    "$(getFilePath og_hw_dim_exec)" "$hardware_dim_value" \
        "$(getFilePath hw_brightness_tracker)" \
        "$(getFilePath hw_brightness_ctl)" \
        "$(getFilePath max_hw_brightness)"
}

function isValidSoftwareDimValue
{
    local -r software_dim_value="$1"
    # bc return 1 when true, 0 when false
    local -ri upper_bound_check="$(bc <<< "$software_dim_value <= 1.0")"
    local -ri lower_bound_check="$(bc <<< "$software_dim_value >= 0.1")"

    [[ "$upper_bound_check" -gt 0 && "$lower_bound_check" -gt 0 ]]
}

function runSoftwareDim
{
    local -r software_dim_value="$1"

    if ! isValidSoftwareDimValue "$software_dim_value"; then
    {
        echo 'Invalid software dim value!'
        echo "Input: $software_dim_value"
        echo "Accepted range: [0.1, 1.0]"
        exit 1
    } 1>&2
    fi

    "$(getFilePath og_sw_dim_exec)" "$software_dim_value" \
        "$(getFilePath sw_brightness_tracker)" \
        "$(getFilePath sw_dim_xrandr_verbose_cache)"
}

function runDim
{
    local -r software_dim_value="$1"
    local -ri hardware_dim_value="$2"

    if isHardwareDimEnabled; then runHardwareDim "$hardware_dim_value"; fi
    runSoftwareDim "$software_dim_value"
}

function main
{
    local    software_dim_value
    local -i hardware_dim_value

    case "$1" in
        --init)
            initSetup
            echo "Ready to use ogdim! Go ahead give it a try!"
            exit 0;
            ;;
        [0-9]*)
            software_dim_value=$1
            hardware_dim_value=${2:-1}
            runDim "$software_dim_value" "$hardware_dim_value"
            exit 0;
            ;;
        "")
            software_dim_value=0.75
            hardware_dim_value=1
            runDim "$software_dim_value" "$hardware_dim_value"
            exit 0;
            ;;
    esac

}

main "$@"

# "/home/spaceface102/.og.d/Dim/brightness_tracker";
# "/sys/class/backlight/intel_backlight/brightness";
# "/sys/class/backlight/intel_backlight/max_brightness";
# OG_DIM_DIR