#!/usr/bin/bash

# script fuzzy searches every line in every file that
# exists recursively relative from current directory, and
# then tells you the file name the line is located in

# Dependent of:
# rg
# fzf
# cut



# !!!! IDEA STOLE FROM https://andrew-quinn.me/fzf/ !!!! #
# small improvement to avoid searching file name with -n
# and --delimiter
# using bat to preview file, --preview-window to jump to line
# config taken straigt from fzf man page

max_depth=${1:--1} # default is -1 aka unbounded
path=${2:-${PWD}} # default is current dir

{
	if [[ ${max_depth} -lt 0 ]]; then
		rg --line-number -e '.' "${path}"
	else
		rg --line-number --max-depth="${max_depth}" -e '.' "${path}"
	fi
} \
| fzf -n '3..-1' --delimiter=':' \
	--preview='bat --style=full --color=always --highlight-line {2} {1}' \
	--preview-window 'up,85%,~3,+{2}+3/2' \
| cut -d ':' -f 1
