#!/usr/bin/bash

# usage: ogpassphrasegen <num words> <word seperator>

wordsFile=/usr/share/dict/words
numWordsInPhrase=${1:-$(shuf -i 2-6 -n 1)}
wordSeperator=${2:-'-'}

shuf -n ${numWordsInPhrase} ${wordsFile} |
	sed -E $'s/^(.*)\'s$/\\1/' | # remove "'s" from the end of words
	tr '[:upper:]' '[:lower:]' |
	paste -s -d "${wordSeperator}"
