#!/usr/bin/bash

# usage: ogpasswordgen [-a, -all, --all-print] [password character length] [list additional special characters to randomly include, ex. '!&^%$']
# ex: ogpasswordgen -a 15 (NOTE: will ignore any addiitonal special characters set)
# ex: ogpasswrodgen 16 '!@#$%'

charRange="a-zA-Z0-9$2"
case "$1" in
	-a|--all|--all-print)
		charRange='[:print:]'
		shift 1		
		;;
esac

declare -r passLength=${1:-$(shuf -i 10-16 -n 1)}
tr --complement --delete "${charRange}" < /dev/urandom | head --bytes="${passLength}"
echo '' # just to have a newline at the end
