#!/usr/bin/bash

password_len="${1:-$(shuf -i 14-28 -n 1)}"
allowed_chars_tr='[:graph:]' 	# all printable chars except space
unallowed_chars_tr="$2"			# if $2 is unset, unallowed_chars_tr='' aka nothing is unallowed

# LC_ALL=C set to ensure single byte chars, as recommened by the tr man page
LC_ALL=C tr --complement --delete "$allowed_chars_tr" < /dev/urandom \
	| tr --delete "$unallowed_chars_tr" \
	| head --bytes="$password_len"
printf '\n'
