#!/usr/bin/bash

# usage: ogpasswordgen <password character length> <additional special characters, eq '!&^%$'>

passLength=${1:-$(shuf -i 10-16 -n 1)}
cat /dev/urandom | tr --complement --delete "a-zA-Z0-9$2" | head --bytes=$passLength
echo # just to have a newline at the end
