#!/usr/bin/bash

wordsFile=/usr/share/dict/words
numOfUniqueWords=$(wc -l $wordsFile | cut -d ' ' -f 1)
userOutputWordCountRequest=${1:-1} # default values if $1 is empty, https://unix.stackexchange.com/questions/338146/bash-defining-variables-with-var-number-default

if [[ userOutputWordCountRequest -gt numOfUniqueWords ]]
then
	echo "NOTE, there WILL be repeate words in the output! Max non repeat size = $numOfUniqueWords words" 1>&2
	shuf -n "$userOutputWordCountRequest" --repeat $wordsFile #--repeat necessary or else will be limited to a max output word count of numOfUniqueWords
else
	shuf -n "$userOutputWordCountRequest" $wordsFile
fi
