#!/usr/bin/bash
librespot \
	--name "librespot-$(hostname)" \
	--bitrate 320 \
	--device-type 'speaker' \
	--cache "${HOME}/.og.d/Librespot" \
	--cache-size-limit '32G' \
	--volume-range '100.0' \
	--initial-volume 100 \
