#!/usr/bin/bash

function generateTrackableEvent()
{
    # assume will only run this function after program checking
    # if at least a taskname has been given
    taskName="$1"
    optionalDescription="$2"
    echo "$(date +'%T') - ${taskName}"
    [ -n "${optionalDescription}" ] &&  echo "${optionalDescription}" | sed 's/^/\t/'
    yes '-' | head -n 80 | paste -s -d '' # seperator bewteen tasks
}

if [[ $# -eq 0 ]]; then
{
    echo 'Please provide task name!'
    echo "usage: $0 '<task name>' '<optional description>'"
    echo "Note the usage of ''. Used to process collection of words as one word"
    exit 1
} 1>&2
fi

todoDir="${TODO_TRACKER_DIR}" # enviorment variable
todaysFileName="$(date +'%F-%a').txt"
fullFileName="${todoDir}/${todaysFileName}"

generateTrackableEvent "$1" "$2" >> "${fullFileName}"
