#!/usr/bin/bash

function main()
{
    local -r defaultFont='mono12'
    local playBeeBool=true
    case "$1" in
        -q|--quite)
            playBeepBool=false
            shift 1 # next param shall be minutes timer shall go for
            ;;
    esac

    local -r startMinutes=${1:-5}; # default is 5 min

    clear
    toilet --font="${defaultFont}" "${startMinutes}:00"
    for ((min=$((startMinutes - 1)); min>=0; min--))
    do
        for ((sec=59; sec>9; sec--))
        do
            sleep 1
            clear
            toilet --font="${defaultFont}" "${min}:${sec}"
        done
        for ((sec=9; sec>=0; sec--))
        do
            sleep 1
            clear
            toilet --font="${defaultFont}" "${min}:0${sec}"
        done
    done

    sleep 1
    clear
    toilet --font="${defaultFont}" "DONE!"

    echo "${startMinutes} elapsed!"
    ${playBeepBool} && aplay -q /usr/share/sounds/GNUstep/Tink.wav
}

main "$@"