#!/usr/bin/bash

# https://www.ddcutil.com/vcpinfo_output/
function main
{
	local -r brightness_feature_code="0x10"
	local user_brightness="$1"
	for bus_number in $(ddcutil detect | awk '/I2C bus:/{print $NF}' | grep -o '[[:digit:]]\+$'); do
		ddcutil --bus "${bus_number}" setvcp "$brightness_feature_code" "$user_brightness"
	done
}

# I don't want to see no error messages from ddcutil, it usually all works fine either way!
main "$@" &> /dev/null &
